### ISSUE TITLE
I bought the pro version of this theme as it clearly stated it had documentation however, there is none.

### ISSUE THREAD

**Issue by denisse-dev** [uicardiodev/hugo-lime#1]
Hello.

I paid for the pro version of this theme as it said it had documentation when in reality there is none.

I gave a 0.5 ⭐️  review on your site due to the lack of documentation but you deleted my review.

Please send the product as advertised (including the documentation) or send me a refund.

**Comment by heyarviind** [comment]
Did you get the documentation?

**Comment by denisse-dev** [comment]
Yes, thank you.

Just a tip, put it on the download page, it was frustating to get a slash where the documentation should be and the project looks amazing.
