### ISSUE TITLE
Purchased Pro but cannot download again

### ISSUE THREAD

**Issue by Trozz** [uicardiodev/hugo-lime#2]
Hi

I purchased the Pro version awhile ago but I have had a drive failure and lost the theme, I went to your site to download it again but your domain has expired, could you resend me the Pro version?

@trozz

**Comment by heyarviind** [comment]
Hi, sorry for the late reply. I was busy with other work and forgot to renew the domain, but i have renewed it now. You can access your account on uicardio and download the theme
